plugins {
    id 'java'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '5.1.+'
}

group = 'com.skyfox'
version = 'a1.0'
archivesBaseName = 'multiparty'

minecraft {
    version = "1.21.1-21.1.145"
    runDir = "run"
    mappings channel: 'official', version: '1.21.1'
}

repositories {
    mavenCentral()
    maven {
        name = "Neoforge"
        url = "https://maven.neoforge.net/"
    }
}

dependencies {
    implementation fg.deobf('net.minecraftforge:forge:1.21.1-21.1.145')
}
