modLoader="javafml"
loaderVersion=">=4.0.0"
license="MIT"

[[mods]]
modId="multiparty"
version="1.0.0"
displayName="MultiParty"
authors=["skyfox"]
description="""
Create/join/leave teams, disable PvP within team, and display team member HUD.
"""
